services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yourbox-leads
    restart: unless-stopped
    ports:
      - "3006:3006"
    env_file:
      - .env.local
    networks:
      - yourbox-network

networks:
  yourbox-network:
    external: true
